DEMO_MAPPING = {
    "source/main.ptx": ["my-demo-book"],
    "source/frontmatter.ptx": [
        "frontmatter",
        "frontmatter-preface",
    ],
    "source/ch-first with spaces.ptx": ["ch-first-without-spaces"],
    "source/sec-first-intro.ptx": ["sec-first-intro"],
    "source/sec-first-examples.ptx": ["sec-first-examples"],
    "source/ex-first.ptx": ["ex-first"],
    "source/ch-empty.ptx": ["ch-empty"],
    "source/ch-features.ptx": ["ch-features"],
    "source/sec-features.ptx": ["sec-features-blocks"],
    "source/ch-generate.ptx": [
        "ch-generate",
        "sec-latex-image",
        "sec-sageplot",
        "sec-asymptote",
        "sec-webwork",
        "sec-youtube",
        "sec-interactive",
        "interactive-infinity",
        "sec-codelens",
    ],
    "source/backmatter.ptx": ["backmatter"],
}
