name: deploy-codespace-template

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Checkout codespace
      uses: actions/checkout@v3
      with:
        repository: pretextbook/pretext-codespace

    - name: Install pretext
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade pretext

    - name: pretext new book
      shell: bash
      run:  |
        python -m pretext new book -d .

    - name: setup git config
      run: |
        # setup the username and email.
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: revert to previous README
      run: git restore README.md

    - name: commit
      run: |
        # Stage the file, commit and push
        git add .
        git commit -m "update to latest `pretext new book`"
        git push origin main


